version: '3.4'

services:
  storeapp:
    image: ${DOCKER_REGISTRY}storeapp
    build:
      context: .
      dockerfile: StoreApp\Dockerfile

  storeapp.service:
    image: ${DOCKER_REGISTRY}storeappservice
    build:
      context: .
      dockerfile: StoreApp.Service\Dockerfile

